In [15]:
import pandas as pd
import os
import re

def load_csv_dataset(file_path):
    return pd.read_csv(file_path)

In [2]:
os.getcwd()

'/Users/finneganlaister-smith/Downloads/DEV ENVIRONMENT/data-science-jupyter-template-main'

In [34]:
match_dataset_latest = load_csv_dataset('footy_project_market_value_rankings/create_dataset_1/CSVs we use often/edited_match_dataset_new_may_30.csv')
match_dataset_latest = match_dataset_latest.drop(columns={'...1', 'Unnamed..0'})
def get_substring_before_number(s):
    match = re.match(r'^[^\d]*', s)
    if match:
        return match.group(0)
    return s
def get_numbers(s):
    numbers = re.findall(r'\d+', s)
    return ''.join(numbers)
for index, row in match_dataset_latest.iterrows():
    if 'Olympics' in row['Match.ID']:
        competition = get_substring_before_number(row['Match.ID']) 
        nums = get_numbers(row['Match.ID'])
        match_dataset_latest.at[index, 'Competition'] = competition
        match_dataset_latest.at[index, 'Match.ID'] = f"{competition}_{nums}"

In [35]:
match_dataset_latest[match_dataset_latest['Competition'] == 'Olympics']

,Match.ID,Competition,Match,Date,Season,Team.1.Name,Team.1.Code,Team.1.Total.Market.Value,Team.1.Players,Team.1.Values.By.Player,...,Team.2.Rank,Team.2.Confederation,score,Score.Difference,Market.Value.Difference,Rank.Difference,Team.1.Num.of.0.Value.Players,Team.2.Num.of.0.Value.Players,Number.of.Valuable.Players.Difference,Standardized_Rank_Difference
49,Olympics_31,Olympics,Iraq vs Denmark,2016-08-04,2016,Iraq,IQ,4500000.0,"['Mohammed Hameed', 'Ali Adnan', 'Dhurgham Ism...","1e+05,1800000,1250000,1e+05,1e+05,650000,4e+05...",...,44,UEFA,0:0 NA,0,-9965000.0,-55,3,0,-3,-0.879403
50,Olympics_13,Olympics,Brazil vs South Africa,2016-08-04,2016,Brazil,BR,227500000.0,"['Weverton', 'Rodrigo Caio', 'Marquinhos', 'Do...","3e+06,5e+06,3.5e+07,5e+06,9e+06,2.5e+07,2.5e+0...",...,67,CAF,0:0 NA,0,221650000.0,58,0,0,0,0.910163
51,Olympics_17,Olympics,Denmark vs South Africa,2016-08-07,2016,Denmark,DK,7765000.0,"['Frederik Børsting', 'Jens Jönsson', 'Lasse V...","4e+05,1e+06,2e+06,2e+05,4e+05,775000,4e+05,5e+...",...,67,CAF,1:0 NA,1,1765000.0,23,0,1,1,0.355873
52,Olympics_11,Olympics,Brazil vs Iraq,2016-08-07,2016,Brazil,BR,210500000.0,"['Weverton', 'Rodrigo Caio', 'Marquinhos', 'Do...","3e+06,5e+06,3.5e+07,5e+06,9e+06,3e+06,2.5e+07,...",...,99,AFC,0:0 NA,0,205810000.0,90,0,3,3,1.416943
53,Olympics_16,Olympics,Denmark vs Brazil,2016-08-10,2016,Denmark,DK,6865000.0,"['Frederik Børsting', 'Jens Jönsson', 'Lasse V...","4e+05,1e+06,2e+06,0,2e+05,4e+05,775000,4e+05,5...",...,9,CONMEBOL,0:4 NA,-4,-181135000.0,-35,1,0,-1,-0.562666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,Olympics_59,Olympics,South Korea vs Mexico,2021-07-31,2021,South Korea,KR,9020000.0,"['Bum-keun Song', 'Jin-gyu Kim', 'Ui-jo Hwang'...","8e+05,325000,2500000,6e+05,7e+05,960000,650000...",...,11,CONCACAF,3:6 NA,-3,-33780000.0,-28,0,0,0,-0.451808
109,Olympics_39,Olympics,Mexico vs Brazil,2021-08-03,2021,Mexico,MX,42800000.0,"['Guillermo Ochoa', 'Vladímir Loroña', 'César ...","2e+06,1800000,6e+06,5e+06,3500000,6e+06,2e+06,...",...,3,CONMEBOL,0:0 NA,0,-177000000.0,-8,0,0,0,-0.135070
110,Olympics_37,Olympics,Japan vs Spain,2021-08-03,2021,Japan,JP,54900000.0,"['Kosei Tani', 'Hiroki Sakai', 'Maya Yoshida',...","1e+05,5500000,3800000,8e+05,8e+05,6e+06,9e+05,...",...,6,UEFA,0:1 NA,-1,-274100000.0,-22,0,0,0,-0.356787
111,Olympics_42,Olympics,Mexico vs Japan,2021-08-06,2021,Mexico,MX,50500000.0,"['Guillermo Ochoa', 'Jorge Sánchez', 'César Mo...","2e+06,3500000,6e+06,5e+06,3500000,6e+06,750000...",...,28,AFC,3:1 NA,2,-21950000.0,17,0,0,0,0.260851
112,Olympics_14,Olympics,Brazil vs Spain,2021-08-06,2021,Brazil,BR,240800000.0,"['Dani Alves', 'Diego Carlos', 'Guilherme Aran...","1600000,4e+07,5e+06,3.8e+07,2.8e+07,1.8e+07,3....",...,6,UEFA,2:1 NA,1,-123200000.0,3,0,0,0,0.039135

In [36]:
match_dataset_latest.to_csv('newest_edited_match_dataset_may_30.csv')